export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OWNER = 'OWNER',
  HR = 'HR',
  FINANCE = 'FINANCE',
  CEO = 'CEO',
  AUDITOR = 'AUDITOR',
  EMPLOYEE = 'EMPLOYEE',
}

export enum EmploymentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ONBOARDING = 'ONBOARDING',
  ON_LEAVE = 'ON_LEAVE',
  TERMINATED = 'TERMINATED',
}

export enum CompensationType {
  SALARY = 'SALARY',
  BONUS = 'BONUS',
  ALLOWANCE = 'ALLOWANCE',
  DEDUCTION = 'DEDUCTION',
}

export enum CompensationFrequency {
  HOURLY = 'HOURLY',
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  SEMIMONTHLY = 'SEMIMONTHLY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  ANNUALLY = 'ANNUALLY',
  ONE_TIME = 'ONE_TIME',
}

export enum PayrollStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  PROCESSING = 'PROCESSING',
  BLOCKCHAIN_PENDING = 'BLOCKCHAIN_PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REJECTED = 'REJECTED',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SKIPPED = 'SKIPPED',
}

export enum ApprovalLevel {
  HR = 'HR',
  FINANCE = 'FINANCE',
  CEO = 'CEO',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum InvitationType {
  EMPLOYEE = 'EMPLOYEE',
  USER = 'USER',
}

export enum AuditAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTERED = 'USER_REGISTERED',
  USER_UPDATED = 'USER_UPDATED',
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED',
  EMPLOYEE_CREATED = 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED',
  EMPLOYEE_DELETED = 'EMPLOYEE_DELETED',
  COMPENSATION_CREATED = 'COMPENSATION_CREATED',
  COMPENSATION_UPDATED = 'COMPENSATION_UPDATED',
  COMPENSATION_ENDED = 'COMPENSATION_ENDED',
  PAYROLL_CREATED = 'PAYROLL_CREATED',
  PAYROLL_UPDATED = 'PAYROLL_UPDATED',
  PAYROLL_GENERATED = 'PAYROLL_GENERATED',
  PAYROLL_SUBMITTED = 'PAYROLL_SUBMITTED',
  PAYROLL_APPROVED = 'PAYROLL_APPROVED',
  PAYROLL_REJECTED = 'PAYROLL_REJECTED',
  PAYROLL_EXECUTED = 'PAYROLL_EXECUTED',
  PAYROLL_CANCELLED = 'PAYROLL_CANCELLED',
  APPROVAL_CREATED = 'APPROVAL_CREATED',
  APPROVAL_APPROVED = 'APPROVAL_APPROVED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  INVITATION_SENT = 'INVITATION_SENT',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  INVITATION_REVOKED = 'INVITATION_REVOKED',
  SETTINGS_UPDATED = 'SETTINGS_UPDATED',
  NOTIFICATION_READ = 'NOTIFICATION_READ',
}

export enum NotificationType {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  APPROVAL = 'APPROVAL',
  PAYROLL = 'PAYROLL',
  INVITATION = 'INVITATION',
  SYSTEM = 'SYSTEM',
}

export enum OrganizationStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}
